/*
 * This file is generated by jOOQ.
 */
package site.markhenrick.mobilespoilers.dal.jooqgenerated;


import site.markhenrick.mobilespoilers.dal.jooqgenerated.tables.Spoilers;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>spoilers</code>.
     */
    public static final Spoilers SPOILERS = Spoilers.SPOILERS;
}
